name: pending-author-response
on:
  issue_comment:
    types: [created]

jobs:
  issue_commented:
    if: ${{ contains(github.event.issue.labels.*.name, 'pending-customer-response') }}
    runs-on: ubuntu-latest
    steps:
      - uses: siegerts/pending-author-response@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pending-response-label: pending-customer-response
          actionable-label: pending-investigation
